apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
replicas:
- count: 3
  name: inventory-client
- count: 3
  name: inventory-client-green
patches:
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: inventory-client-green
  target:
    kind: Service
    name: inventory-client
