apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
replicas:
- count: 3
  name: inventory-client
- count: 0
  name: inventory-client-green
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
  target:
    kind: Deployment
    name: inventory-client-green
images:
- name: hylmar/inventory-client:BLUE
  newTag: 1.0.10-SNAPSHOT
- name: hylmar/inventory-client:GREEN
  newTag: 1.0.10-SNAPSHOT
