apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: inventory
build:
  artifacts:
  - image: hylmar/inventory
    context: .
    jib:
      type: maven
deploy:
  kustomize:
    paths:
    - kustomization/base
