apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: inventory
build:
  local:
    push: true
  artifacts:
  - image: hylmar/inventory
    context: .
    jib:
      type: maven
deploy:
  kustomize:
    paths:
    - kustomization/overlays/dev
