spring:

  application:
    name: inventory

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  cloud:
    stream:
      function:
        definition: proc

      bindings:
        proc-out-0:
          contentType: application/json
          destination: inventory-out
        proc-in-0:
          contentType: application/json
          destination: inventory-in
          group: inventory
      




