kind: ConfigMap
apiVersion: v1
metadata:
  name: inventory-configmap
data:
  RABBITMQ_HOST: rabbitmq.rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: default_user_VK5bQ_W9cwMVcunrOsT
  RABBITMQ_PASSWORD: 6XnSgFNuvAsK0MxcZYR9jxrD2F0u0Oiw