apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- drain-green-deployment.yaml
replicas:
- count: 3
  name: inventory
images:
- name: hylmar/inventory:CHANGEME
  newTag: 1.0.5-SNAPSHOT
