apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
replicas:
- count: 3
  name: inventory
- count: 0
  name: inventory-green
images:
- name: hylmar/inventory:BLUE
  newTag: 1.0.12-SNAPSHOT
- name: hylmar/inventory:CHANGEME
  newTag: 1.0.12-SNAPSHOT
- name: hylmar/inventory:GREEN
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/container/imagePullPolicy
      value: Never
  target:
    kind: Deployment
    name: inventory-green
