spring:

  application:
    name: inventory-client

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  rabbitmq:
#    host: ${RABBITMQ_HOST}
#    port: ${RABBITMQ_PORT}
#    username: ${RABBITMQ_USERNAME}
#    password: ${RABBITMQ_PASSWORD}

  cloud:
    stream:
      function:
        definition: orderEventProducer

      bindings:
        orderEventProducer-out-0:
          contentType: application/json
          destination: inventory-inx

      rabbit:
        bindings:
          orderEventProducer-out-0:
            declareExchange: false



