apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
replicas:
- count: 3
  name: inventory
images:
- name: hylmar/inventory:CHANGEME
  newTag: 1.0.1-SNAPSHOT
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: inventory-green
  target:
    kind: Deployment
    name: inventory
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: inventory-green
  target:
    kind: Service
    name: inventory
