apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- deployment-green.yaml
replicas:
- count: 3
  name: inventory
- count: 3
  name: inventory-green
images:
- name: hylmar/inventory:CHANGEME
  newTag: 1.0.8-SNAPSHOT
- name: hylmar/inventory:GREEN
  newTag: 1.0.9-SNAPSHOT
patches:
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: inventory-green
  target:
    kind: Service
    name: inventory
