apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: inventory
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory
  name: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - image: hylmar/inventory:1.0.17-SNAPSHOT
        imagePullPolicy: Always
        name: inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-green
  name: inventory-green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inventory-green
  template:
    metadata:
      labels:
        app: inventory-green
    spec:
      containers:
      - image: hylmar/inventory:1.0.17-SNAPSHOT
        imagePullPolicy: Never
        name: inventory-green
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: test-queue
  namespace: rabbitmq
spec:
  name: test-queue
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
