# See https://kubectl.docs.kubernetes.io/pages/examples/kustomize.html for reference.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - deployment-green.yaml
  - service.yaml
  - ingress.yaml
